# Generated by Django 3.2.25 on 2024-06-10 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_ideas', models.JSONField(default=list)),
                ('groups', models.ManyToManyField(blank=True, related_name='eventi_user_set', related_query_name='eventi_user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='eventi_user_set', related_query_name='eventi_user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('interests', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_preferences', to='eventi_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='DateIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=70)),
                ('budget', models.CharField(choices=[('cheap', '$0-$20'), ('medium', '$40-$80'), ('expensive', '$80 or more')], max_length=9)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventi_app.user')),
            ],
        ),
    ]
